name: "Run tests in container"
description: "Run all the tests in container"
runs:
  using: "composite"
  steps:
    - name: test
      shell: sh
      run: |
        docker run --env LOGSQUIRL_BUILD_ROOT=$LOGSQUIRL_BUILD_ROOT -v "$LOGSQUIRL_WORKSPACE":/usr/local ${{ matrix.config.container }} /bin/bash -c "cd /usr/local/$LOGSQUIRL_BUILD_ROOT && ctest --verbose"

