version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci"
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/docker/ubuntu24.04"
    schedule:
      interval: "weekly"
    labels:
      - "ci"
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/docker/oracle10"
    schedule:
      interval: "weekly"
    labels:
      - "ci"
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/docker/fedora43"
    schedule:
      interval: "weekly"
    labels:
      - "ci"
      - "dependencies"
