# Fails when a file outside the engine -- any directory under HEADERS_ROOT
# but ENGINE_DIRS: the widget library, the application, the Open Log File,
# the Log Formats, the plugins and every other -- includes the index worker's
# header, logdataworker.h -- directly, or through any header of the project,
# the log data's among them. The worker is how the log data indexes a Log
# File; nothing above the engine names it, and the job values the operation
# queue hands it live in a header of their own (#549).
#
# Every header under HEADERS_ROOT is resolved by its file name, the one beside
# the including file first; a header that is not found there (Qt's, the
# standard library's, one generated by the build) is not followed.
#
# Usage: cmake -DENGINE_DIRS=<logdata>
#              -DHEADERS_ROOT=<src>
#              -P index_worker_stays_in_the_engine.cmake

# Script mode sets no policies; if(IN_LIST) needs CMP0057.
cmake_minimum_required(VERSION 3.16)

set(_worker "logdataworker.h")

if(NOT HEADERS_ROOT OR NOT IS_DIRECTORY "${HEADERS_ROOT}")
  message(FATAL_ERROR "HEADERS_ROOT is not a directory: '${HEADERS_ROOT}'")
endif()
string(REPLACE "|" ";" _engine_dirs "${ENGINE_DIRS}")
if(NOT _engine_dirs)
  message(FATAL_ERROR "ENGINE_DIRS is empty")
endif()
foreach(_dir IN LISTS _engine_dirs)
  if(NOT IS_DIRECTORY "${HEADERS_ROOT}/${_dir}")
    message(FATAL_ERROR "Not a directory: '${HEADERS_ROOT}/${_dir}'")
  endif()
endforeach()

# Every directory under HEADERS_ROOT but the engine's.
file(GLOB _children LIST_DIRECTORIES TRUE "${HEADERS_ROOT}/*")
set(_sources_dirs "")
foreach(_child IN LISTS _children)
  get_filename_component(_name "${_child}" NAME)
  if(IS_DIRECTORY "${_child}" AND NOT _name IN_LIST _engine_dirs)
    list(APPEND _sources_dirs "${_child}")
  endif()
endforeach()

file(GLOB_RECURSE _headers "${HEADERS_ROOT}/*.h" "${HEADERS_ROOT}/*.hpp")
if(NOT _headers)
  message(FATAL_ERROR "No headers found under ${HEADERS_ROOT}")
endif()

# Every header by its file name; a name several directories share lists all.
foreach(_header IN LISTS _headers)
  get_filename_component(_name "${_header}" NAME)
  list(APPEND "_by_name_${_name}" "${_header}")
endforeach()
if(NOT DEFINED "_by_name_${_worker}")
  message(FATAL_ERROR "${_worker} not found under ${HEADERS_ROOT}")
endif()

# The project headers a file includes, into out_var.
function(project_includes file out_var)
  get_filename_component(_dir "${file}" DIRECTORY)
  file(STRINGS "${file}" _lines REGEX "^[ \t]*#[ \t]*include[ \t]*[<\"]")
  set(_found "")
  foreach(_line IN LISTS _lines)
    string(REGEX REPLACE "^[ \t]*#[ \t]*include[ \t]*[<\"]([^>\"]+)[>\"].*$" "\\1" _included
                         "${_line}")
    if(EXISTS "${_dir}/${_included}" AND NOT IS_DIRECTORY "${_dir}/${_included}")
      get_filename_component(_resolved "${_dir}/${_included}" ABSOLUTE)
      list(APPEND _found "${_resolved}")
    else()
      get_filename_component(_name "${_included}" NAME)
      if(DEFINED "_by_name_${_name}")
        list(APPEND _found ${_by_name_${_name}})
      endif()
    endif()
  endforeach()
  list(REMOVE_DUPLICATES _found)
  set(${out_var} "${_found}" PARENT_SCOPE)
endfunction()

set(_index 0)
foreach(_header IN LISTS _headers)
  project_includes("${_header}" _includes)
  set("_includes_${_index}" "${_includes}")
  math(EXPR _index "${_index} + 1")
endforeach()

# The headers that reach the worker's, each with the one it reaches it
# through, found by growing the set from the worker's own until it stops.
set(_reaching ${_by_name_${_worker}})
foreach(_header IN LISTS _reaching)
  set("_through_${_header}" "")
endforeach()
set(_grew TRUE)
while(_grew)
  set(_grew FALSE)
  set(_index 0)
  foreach(_header IN LISTS _headers)
    if(NOT _header IN_LIST _reaching)
      foreach(_included IN LISTS "_includes_${_index}")
        if(_included IN_LIST _reaching)
          list(APPEND _reaching "${_header}")
          set("_through_${_header}" "${_included}")
          set(_grew TRUE)
          break()
        endif()
      endforeach()
    endif()
    math(EXPR _index "${_index} + 1")
  endforeach()
endwhile()

set(_sources "")
foreach(_dir IN LISTS _sources_dirs)
  file(GLOB_RECURSE _found "${_dir}/*.h" "${_dir}/*.hpp" "${_dir}/*.cpp")
  list(APPEND _sources ${_found})
endforeach()
if(NOT _sources)
  message(FATAL_ERROR "No sources found under ${_sources_dirs}")
endif()

set(_offenders "")
foreach(_source IN LISTS _sources)
  get_filename_component(_source "${_source}" ABSOLUTE)
  project_includes("${_source}" _includes)
  foreach(_included IN LISTS _includes)
    if(_included IN_LIST _reaching)
      file(RELATIVE_PATH _chain "${HEADERS_ROOT}" "${_source}")
      set(_step "${_included}")
      while(_step)
        get_filename_component(_name "${_step}" NAME)
        string(APPEND _chain " -> ${_name}")
        set(_step "${_through_${_step}}")
      endwhile()
      list(APPEND _offenders "${_chain}")
      break()
    endif()
  endforeach()
endforeach()

if(_offenders)
  list(JOIN _offenders "\n  " _report)
  message(FATAL_ERROR "The index worker's header is included outside the engine:\n  ${_report}")
endif()

list(LENGTH _sources _count)
list(LENGTH _sources_dirs _dirs_count)
message(STATUS "${_count} files in ${_dirs_count} directories outside the engine, "
               "none includes the index worker's header")
