# NSIS script creating the Windows installer for logsquirl

# Is passed to the script using -DVERSION=$(git describe) on the command line
!ifndef VERSION
    !define VERSION 'dev-build'
!endif

!ifndef PLATFORM
    !define PLATFORM 'unknown'
!endif

!ifndef QT_MAJOR
    !define QT_MAJOR 'Qt5'
!endif

# Headers
!include "MUI2.nsh"
!include "LogicLib.nsh"
!include "FileAssociation.nsh"
; PRODUCT_VI_NAME, _COMPANY, _COPYRIGHT and _VERSION: the version resource of
; the executables, generated by CMake (cmake/version_info.nsh.in) and copied
; here by prepare_release.cmd, so setup.exe names the same product (#445)
!include "version_info.nsh"

# General
OutFile "logsquirl-win-${PLATFORM}-setup.exe"

XpStyle on

SetCompressor /SOLID lzma

; Registry key to keep track of the directory we are installed in
!ifdef ARCH32
  InstallDir "$PROGRAMFILES\logsquirl"
!else
  InstallDir "$PROGRAMFILES64\logsquirl"
!endif
InstallDirRegKey HKLM Software\logsquirl ""

; logsquirl icon
; !define MUI_ICON logsquirl.ico

RequestExecutionLevel admin

Name "LogSquirl"
Caption "LogSquirl ${VERSION} Setup"

# Pages
!define MUI_WELCOMEPAGE_TITLE "Welcome to the LogSquirl ${VERSION} Setup Wizard"
!define MUI_WELCOMEPAGE_TEXT "This wizard will guide you through the installation of LogSquirl\
, a fast, advanced log explorer.$\r$\n$\r$\n\
logsquirl and the Qt libraries are released under the GPL, see \
the COPYING and NOTICE files.$\r$\n$\r$\n$_CLICK"

!insertmacro MUI_PAGE_WELCOME
; The privacy policy is shown before anything is installed, and the next page
; offers to turn the update check off: code signing through the SignPath
; Foundation asks both of software that contacts a server on its own (#445).
; It is information, not a licence to accept, so the button goes on as Next.
!define MUI_PAGE_HEADER_TEXT "Privacy policy"
!define MUI_PAGE_HEADER_SUBTEXT "What LogSquirl sends over the network, and how to turn it off."
!define MUI_LICENSEPAGE_TEXT_TOP "Press Page Down to see the rest of the privacy policy."
!define MUI_LICENSEPAGE_TEXT_BOTTOM "The next page lets you turn the automatic update check off."
!define MUI_LICENSEPAGE_BUTTON "$(^NextBtn)"
!insertmacro MUI_PAGE_LICENSE "PRIVACY.md"
!insertmacro MUI_PAGE_COMPONENTS
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_WELCOME
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_UNPAGE_FINISH

# Languages
!insertmacro MUI_LANGUAGE "English"

# Version resource of setup.exe, the same as the executables' (#445)
VIProductVersion "${PRODUCT_VI_VERSION}"
VIFileVersion "${PRODUCT_VI_VERSION}"
VIAddVersionKey /LANG=${LANG_ENGLISH} "ProductName" "${PRODUCT_VI_NAME}"
VIAddVersionKey /LANG=${LANG_ENGLISH} "CompanyName" "${PRODUCT_VI_COMPANY}"
VIAddVersionKey /LANG=${LANG_ENGLISH} "LegalCopyright" "${PRODUCT_VI_COPYRIGHT}"
VIAddVersionKey /LANG=${LANG_ENGLISH} "FileDescription" "${PRODUCT_VI_NAME} Setup"
VIAddVersionKey /LANG=${LANG_ENGLISH} "FileVersion" "${PRODUCT_VI_VERSION}"
VIAddVersionKey /LANG=${LANG_ENGLISH} "ProductVersion" "${PRODUCT_VI_VERSION}"

# Installer sections
Section "logsquirl" logsquirl
    ; Prevent this section from being unselected
    SectionIn RO

    SetOutPath $INSTDIR
    File release\logsquirl.exe
    ; The command line tool, installed beside the application (#430)
    File release\logsquirl_grep.exe
    File release\logsquirl_crashpad_handler.exe
    File release\logsquirl_minidump_dump.exe
    File release\tbb12.dll
    File release\hs.dll
    File release\hs_avx2.dll

    File COPYING
    File NOTICE
    File README.md
    File PRIVACY.md
    File DOCUMENTATION.md
    File release\documentation.html

    ; Create the 'sendto' link
    CreateShortCut "$SENDTO\logsquirl.lnk" "$INSTDIR\logsquirl.exe" "" "$INSTDIR\logsquirl.exe" 0

    ; Register as an otion (but not main handler) for some files (.txt, .Log, .cap)
    WriteRegStr HKCR "Applications\logsquirl.exe" "" ""
    WriteRegStr HKCR "Applications\logsquirl.exe\shell" "" "open"
    WriteRegStr HKCR "Applications\logsquirl.exe\shell\open" "LogSquirl log viewer" "logsquirl"
    WriteRegStr HKCR "Applications\logsquirl.exe\shell\open\command" "" '"$INSTDIR\logsquirl.exe" "%1"'
    WriteRegStr HKCR "*\OpenWithList\logsquirl.exe" "" ""
    WriteRegStr HKCR ".txt\OpenWithList\logsquirl.exe" "" ""
    WriteRegStr HKCR ".Log\OpenWithList\logsquirl.exe" "" ""
    WriteRegStr HKCR ".cap\OpenWithList\logsquirl.exe" "" ""

    ; Register uninstaller
    WriteRegExpandStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\logsquirl"\
"UninstallString" '"$INSTDIR\Uninstall.exe"'
    WriteRegExpandStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\logsquirl"\
"InstallLocation" "$INSTDIR"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\logsquirl" "DisplayName" "LogSquirl"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\logsquirl" "DisplayVersion" "${VERSION}"
    WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\logsquirl" "NoModify" "1"
    WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\logsquirl" "NoRepair" "1"

    ; Create uninstaller
    WriteUninstaller "$INSTDIR\Uninstall.exe"
SectionEnd

Section "Qt Runtime libraries" qtlibs
    SetOutPath $INSTDIR
    File release\${QT_MAJOR}Core.dll
    File release\${QT_MAJOR}Gui.dll
    File release\${QT_MAJOR}Network.dll
    File release\${QT_MAJOR}Widgets.dll
    File release\${QT_MAJOR}Concurrent.dll
    File release\${QT_MAJOR}Xml.dll
!if ${QT_MAJOR} == "Qt6"
    File release\${QT_MAJOR}Svg.dll
!endif

    SetOutPath $INSTDIR\platforms
    File release\platforms\qwindows.dll

    ; SVG support for the check marks, arrows and close buttons of the themes
    SetOutPath $INSTDIR\imageformats
    File release\imageformats\qsvg.dll
    SetOutPath $INSTDIR\iconengines
    File release\iconengines\qsvgicon.dll
    SetOutPath $INSTDIR\styles
!if ${QT_MAJOR} == "Qt6"
    File release\styles\qmodernwindowsstyle.dll
!else
    File release\styles\qwindowsvistastyle.dll
!endif

    ; Qt TLS backends (OpenSSL for HTTPS, SChannel as OS-native fallback)
    SetOutPath $INSTDIR\tls
    File release\tls\qopensslbackend.dll
    File release\tls\qschannelbackend.dll

SectionEnd

Section "MSVC Runtime libraries" vcruntime
    SetOutPath $INSTDIR
    File release\msvcp140.dll
    File release\msvcp140_1.dll
    File release\vcruntime140.dll
    
!if ${PLATFORM} == "x64"
    File release\vcruntime140_1.dll

    File release\libcrypto-3-x64.dll
    File release\libssl-3-x64.dll
!else
    File release\libcrypto-3.dll
    File release\libssl-3.dll
!endif

SectionEnd

Section "Create Start menu shortcut" shortcut
    SetShellVarContext all
    CreateShortCut "$SMPROGRAMS\logsquirl.lnk" "$INSTDIR\logsquirl.exe" "" "$INSTDIR\logsquirl.exe" 0
SectionEnd

Section /o "Associate with .log files" associate
    ${registerExtension} "$INSTDIR\logsquirl.exe" ".log" "Log file"
SectionEnd

; Selected by default: the update check is on unless it is unticked here. The
; section itself installs nothing; the hidden one after it acts on the choice.
Section "Check for updates automatically" updatecheck
SectionEnd

; Always runs, so an install with the box ticked also removes the file an
; earlier install with it unticked left. While the file is there, LogSquirl
; does not check for updates, whatever its settings say
; (src/versioncheck/include/installoptout.h, #445).
; A silent install (/S) shows no component page, so nobody chose anything: it
; leaves the file as it is, and an administrator's opt-out survives an upgrade.
Section "-Update check choice"
    ${If} ${Silent}
        ; keep what an earlier install or an administrator left
    ${ElseIf} ${SectionIsSelected} ${updatecheck}
        Delete "$INSTDIR\logsquirl_no_update_check"
    ${Else}
        SetOutPath $INSTDIR
        FileOpen $0 "$INSTDIR\logsquirl_no_update_check" w
        FileClose $0
    ${EndIf}
SectionEnd

# Descriptions
!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
    !insertmacro MUI_DESCRIPTION_TEXT ${logsquirl} "The core files required to use logsquirl."
    !insertmacro MUI_DESCRIPTION_TEXT ${qtlibs} "Needed by logsquirl, you have to install these unless \
you already have the Qt development kit installed."
    !insertmacro MUI_DESCRIPTION_TEXT ${vcruntime} "Needed by logsquirl, you have to install these unless \
you already have the Microsoft Visual C++ 2017 Redistributable installed."
    !insertmacro MUI_DESCRIPTION_TEXT ${shortcut} "Create a shortcut in the Start menu for logsquirl."
    !insertmacro MUI_DESCRIPTION_TEXT ${associate} "Make logsquirl the default viewer for .log files."
    !insertmacro MUI_DESCRIPTION_TEXT ${updatecheck} "At most once a week, when it starts, LogSquirl downloads \
a small file from GitHub to see whether a newer version is out. Untick to turn this off for this installation."
!insertmacro MUI_FUNCTION_DESCRIPTION_END

# Uninstaller
Section "Uninstall"
    Delete "$INSTDIR\Uninstall.exe"

    Delete "$INSTDIR\logsquirl.exe"
    Delete "$INSTDIR\logsquirl_grep.exe"
    Delete "$INSTDIR\logsquirl_crashpad_handler.exe"
    Delete "$INSTDIR\logsquirl_minidump_dump.exe"
    Delete "$INSTDIR\README.md"
    Delete "$INSTDIR\PRIVACY.md"
    Delete "$INSTDIR\logsquirl_no_update_check"
    Delete "$INSTDIR\COPYING"
    Delete "$INSTDIR\NOTICE"
    Delete "$INSTDIR\DOCUMENTATION.md"
    Delete "$INSTDIR\documentation.html"
    Delete "$INSTDIR\Qt5Widgets.dll"
    Delete "$INSTDIR\Qt5Core.dll"
    Delete "$INSTDIR\Qt5Gui.dll"
    Delete "$INSTDIR\Qt5Network.dll"
    Delete "$INSTDIR\Qt5Concurrent.dll"
    Delete "$INSTDIR\Qt5Xml.dll"
    Delete "$INSTDIR\Qt6Widgets.dll"
    Delete "$INSTDIR\Qt6Core.dll"
    Delete "$INSTDIR\Qt6Gui.dll"
    Delete "$INSTDIR\Qt6Network.dll"
    Delete "$INSTDIR\Qt6Concurrent.dll"
    Delete "$INSTDIR\Qt6Xml.dll"
    Delete "$INSTDIR\Qt6Core5Compat.dll"
    Delete "$INSTDIR\Qt6Svg.dll"
    Delete "$INSTDIR\platforms\qwindows.dll"
    RMDir "$INSTDIR\platforms"
    Delete "$INSTDIR\imageformats\qsvg.dll"
    RMDir "$INSTDIR\imageformats"
    Delete "$INSTDIR\iconengines\qsvgicon.dll"
    RMDir "$INSTDIR\iconengines"
    Delete "$INSTDIR\styles\qmodernwindowsstyle.dll"
    ; Clean up legacy Qt style plugins from previous installations
    Delete "$INSTDIR\styles\qwindowsvistastyle.dll"
    RMDir "$INSTDIR\styles"
    Delete "$INSTDIR\tls\qopensslbackend.dll"
    Delete "$INSTDIR\tls\qschannelbackend.dll"
    RMDir "$INSTDIR\tls"
    Delete "$INSTDIR\msvcp140.dll"
    Delete "$INSTDIR\msvcp140_1.dll"
    Delete "$INSTDIR\vcruntime140.dll"
    Delete "$INSTDIR\vcruntime140_1.dll"
    Delete "$INSTDIR\tbb12.dll"
    Delete "$INSTDIR\hs.dll"
    Delete "$INSTDIR\hs_avx2.dll"
    Delete "$INSTDIR\libcrypto-3-x64.dll"
    Delete "$INSTDIR\libssl-3-x64.dll"
    Delete "$INSTDIR\libcrypto-3.dll"
    Delete "$INSTDIR\libssl-3.dll"
    ; Clean up legacy OpenSSL 1.1 files from previous installations
    Delete "$INSTDIR\libcrypto-1_1-x64.dll"
    Delete "$INSTDIR\libssl-1_1-x64.dll"
    Delete "$INSTDIR\libcrypto-1_1.dll"
    Delete "$INSTDIR\libssl-1_1.dll"
    Delete "$INSTDIR\mimalloc.dll"
    Delete "$INSTDIR\mimalloc_override.dll"
    Delete "$INSTDIR\mimalloc_redirect.dll"
    Delete "$INSTDIR\mimalloc_redirect32.dll"
    Delete "$INSTDIR\mimalloc-redirect.dll"
    Delete "$INSTDIR\mimalloc-redirect32.dll"
    RMDir "$INSTDIR"

    ; Remove settings in %appdata%
    Delete "$APPDATA\logsquirl\logsquirl.ini"
    RMDir "$APPDATA\logsquirl"

    DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\logsquirl"

    ; Remove the file associations
    ${unregisterExtension} ".log" "Log file"

    DeleteRegKey HKCR "*\OpenWithList\logsquirl.exe"
    DeleteRegKey HKCR ".txt\OpenWithList\logsquirl.exe"
    DeleteRegKey HKCR ".Log\OpenWithList\logsquirl.exe"
    DeleteRegKey HKCR ".cap\OpenWithList\logsquirl.exe"
    DeleteRegKey HKCR "Applications\logsquirl.exe\shell\open\command"
    DeleteRegKey HKCR "Applications\logsquirl.exe\shell\open"
    DeleteRegKey HKCR "Applications\logsquirl.exe\shell"
    DeleteRegKey HKCR "Applications\logsquirl.exe"

    ; The 'Send to' shortcut of the user uninstalling, who is usually the one
    ; who installed (#506)
    Delete "$SENDTO\logsquirl.lnk"

    ; Remove the shortcut, if any
    SetShellVarContext all
    Delete "$SMPROGRAMS\logsquirl.lnk"
SectionEnd

