# NSIS script creating the Windows installer for logsquirl

# Is passed to the script using -DVERSION=$(git describe) on the command line
!ifndef VERSION
    !define VERSION 'dev-build'
!endif

!ifndef PLATFORM
    !define PLATFORM 'unknown'
!endif

!ifndef QT_MAJOR
    !define QT_MAJOR 'Qt5'
!endif

# Headers
!include "MUI2.nsh"
!include "LogicLib.nsh"
!include "FileAssociation.nsh"
; The file types LogSquirl opens: the registry macros, and the types, sections
; and descriptions generated from cmake/FileTypes.cmake, which
; prepare_release.cmd copies here (#719)
!include "FileTypes.nsh"
!include "logsquirl_file_types.nsh"
; PRODUCT_VI_NAME, _COMPANY, _COPYRIGHT and _VERSION: the version resource of
; the executables, generated by CMake (cmake/version_info.nsh.in) and copied
; here by prepare_release.cmd, so setup.exe names the same product (#445)
!include "version_info.nsh"

# General
OutFile "logsquirl-win-${PLATFORM}-setup.exe"

XpStyle on

SetCompressor /SOLID lzma

; Registry key to keep track of the directory we are installed in
!ifdef ARCH32
  InstallDir "$PROGRAMFILES\logsquirl"
!else
  InstallDir "$PROGRAMFILES64\logsquirl"
!endif
InstallDirRegKey HKLM Software\logsquirl ""

; logsquirl icon
; !define MUI_ICON logsquirl.ico

RequestExecutionLevel admin

Name "LogSquirl"
Caption "LogSquirl ${VERSION} Setup"

# Pages
!define MUI_WELCOMEPAGE_TITLE "Welcome to the LogSquirl ${VERSION} Setup Wizard"
!define MUI_WELCOMEPAGE_TEXT "This wizard will guide you through the installation of LogSquirl\
, a fast, advanced log explorer.$\r$\n$\r$\n\
logsquirl and the Qt libraries are released under the GPL, see \
the COPYING and NOTICE files.$\r$\n$\r$\n$_CLICK"

!insertmacro MUI_PAGE_WELCOME
; The privacy policy is shown before anything is installed, and the next page
; offers to turn the update check off: code signing through the SignPath
; Foundation asks both of software that contacts a server on its own (#445).
; It is information, not a licence to accept, so the button goes on as Next.
!define MUI_PAGE_HEADER_TEXT "Privacy policy"
!define MUI_PAGE_HEADER_SUBTEXT "What LogSquirl sends over the network, and how to turn it off."
!define MUI_LICENSEPAGE_TEXT_TOP "Press Page Down to see the rest of the privacy policy."
!define MUI_LICENSEPAGE_TEXT_BOTTOM "The next page lets you turn the automatic update check off."
!define MUI_LICENSEPAGE_BUTTON "$(^NextBtn)"
!insertmacro MUI_PAGE_LICENSE "PRIVACY.md"
!define MUI_PAGE_CUSTOMFUNCTION_PRE ComponentsPagePre
!insertmacro MUI_PAGE_COMPONENTS
; The file types LogSquirl opens get a page of their own (#719): the same
; components page again, showing only the file type sections. Each page hides
; the other's sections when it is shown.
!define MUI_PAGE_HEADER_TEXT "File types"
!define MUI_PAGE_HEADER_SUBTEXT "Choose which files open in LogSquirl."
!define MUI_COMPONENTSPAGE_TEXT_TOP "LogSquirl opens the checked file types on a double-click, and they show its \
document icon. Explorer offers LogSquirl under Open with for all of them, checked or not, and for .gz and .zip files."
!define MUI_COMPONENTSPAGE_TEXT_COMPLIST "File types to open with LogSquirl:"
!define MUI_PAGE_CUSTOMFUNCTION_PRE FileTypesPagePre
!insertmacro MUI_PAGE_COMPONENTS
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_WELCOME
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_UNPAGE_FINISH

# Languages
!insertmacro MUI_LANGUAGE "English"

# Version resource of setup.exe, the same as the executables' (#445)
VIProductVersion "${PRODUCT_VI_VERSION}"
VIFileVersion "${PRODUCT_VI_VERSION}"
VIAddVersionKey /LANG=${LANG_ENGLISH} "ProductName" "${PRODUCT_VI_NAME}"
VIAddVersionKey /LANG=${LANG_ENGLISH} "CompanyName" "${PRODUCT_VI_COMPANY}"
VIAddVersionKey /LANG=${LANG_ENGLISH} "LegalCopyright" "${PRODUCT_VI_COPYRIGHT}"
VIAddVersionKey /LANG=${LANG_ENGLISH} "FileDescription" "${PRODUCT_VI_NAME} Setup"
VIAddVersionKey /LANG=${LANG_ENGLISH} "FileVersion" "${PRODUCT_VI_VERSION}"
VIAddVersionKey /LANG=${LANG_ENGLISH} "ProductVersion" "${PRODUCT_VI_VERSION}"

# Installer sections
; The names of the components, which the file type page hides and the
; components page shows again.
!define SECTION_TEXT_LOGSQUIRL "logsquirl"
!define SECTION_TEXT_QTLIBS "Qt Runtime libraries"
!define SECTION_TEXT_VCRUNTIME "MSVC Runtime libraries"
!define SECTION_TEXT_SHORTCUT "Create Start menu shortcut"
!define SECTION_TEXT_UPDATECHECK "Check for updates automatically"

Section "${SECTION_TEXT_LOGSQUIRL}" logsquirl
    ; Prevent this section from being unselected
    SectionIn RO

    SetOutPath $INSTDIR
    File release\logsquirl.exe
    ; The command line tool, installed beside the application (#430)
    File release\logsquirl_grep.exe
    File release\logsquirl_crashpad_handler.exe
    File release\logsquirl_minidump_dump.exe
    File release\tbb12.dll
    File release\hs.dll
    File release\hs_avx2.dll

    File COPYING
    File NOTICE
    File README.md
    File PRIVACY.md
    File DOCUMENTATION.md
    File release\documentation.html

    ; Create the 'sendto' link
    CreateShortCut "$SENDTO\logsquirl.lnk" "$INSTDIR\logsquirl.exe" "" "$INSTDIR\logsquirl.exe" 0

    ; Register as an otion (but not main handler) for some files (.txt, .Log, .cap)
    WriteRegStr HKCR "Applications\logsquirl.exe" "" ""
    WriteRegStr HKCR "Applications\logsquirl.exe\shell" "" "open"
    WriteRegStr HKCR "Applications\logsquirl.exe\shell\open" "LogSquirl log viewer" "logsquirl"
    WriteRegStr HKCR "Applications\logsquirl.exe\shell\open\command" "" '"$INSTDIR\logsquirl.exe" "%1"'
    WriteRegStr HKCR "*\OpenWithList\logsquirl.exe" "" ""
    WriteRegStr HKCR ".txt\OpenWithList\logsquirl.exe" "" ""
    WriteRegStr HKCR ".Log\OpenWithList\logsquirl.exe" "" ""
    WriteRegStr HKCR ".cap\OpenWithList\logsquirl.exe" "" ""

    ; The file types (#719): a ProgID with the document icon for each, and
    ; LogSquirl under "Open with" for all of them, whatever the file type page
    ; says; the file type sections below make it the default for the checked
    ; ones. The .log association of an earlier version (the ProgID "Log file")
    ; gives .log back first, to the ProgID it had before.
    ${UnRegisterExtension} ".log" "Log file"
    !insertmacro LogSquirlRegisterFileTypes

    ; Register uninstaller
    WriteRegExpandStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\logsquirl"\
"UninstallString" '"$INSTDIR\Uninstall.exe"'
    WriteRegExpandStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\logsquirl"\
"InstallLocation" "$INSTDIR"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\logsquirl" "DisplayName" "LogSquirl"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\logsquirl" "DisplayVersion" "${VERSION}"
    WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\logsquirl" "NoModify" "1"
    WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\logsquirl" "NoRepair" "1"

    ; Create uninstaller
    WriteUninstaller "$INSTDIR\Uninstall.exe"
SectionEnd

Section "${SECTION_TEXT_QTLIBS}" qtlibs
    SetOutPath $INSTDIR
    File release\${QT_MAJOR}Core.dll
    File release\${QT_MAJOR}Gui.dll
    File release\${QT_MAJOR}Network.dll
    File release\${QT_MAJOR}Widgets.dll
    File release\${QT_MAJOR}Concurrent.dll
    File release\${QT_MAJOR}Xml.dll
!if ${QT_MAJOR} == "Qt6"
    File release\${QT_MAJOR}Svg.dll
!endif

    SetOutPath $INSTDIR\platforms
    File release\platforms\qwindows.dll

    ; SVG support for the check marks, arrows and close buttons of the themes
    SetOutPath $INSTDIR\imageformats
    File release\imageformats\qsvg.dll
    SetOutPath $INSTDIR\iconengines
    File release\iconengines\qsvgicon.dll
    SetOutPath $INSTDIR\styles
!if ${QT_MAJOR} == "Qt6"
    File release\styles\qmodernwindowsstyle.dll
!else
    File release\styles\qwindowsvistastyle.dll
!endif

    ; Qt TLS backends (OpenSSL for HTTPS, SChannel as OS-native fallback)
    SetOutPath $INSTDIR\tls
    File release\tls\qopensslbackend.dll
    File release\tls\qschannelbackend.dll

SectionEnd

Section "${SECTION_TEXT_VCRUNTIME}" vcruntime
    SetOutPath $INSTDIR
    File release\msvcp140.dll
    File release\msvcp140_1.dll
    File release\vcruntime140.dll
    
!if ${PLATFORM} == "x64"
    File release\vcruntime140_1.dll

    File release\libcrypto-3-x64.dll
    File release\libssl-3-x64.dll
!else
    File release\libcrypto-3.dll
    File release\libssl-3.dll
!endif

SectionEnd

Section "${SECTION_TEXT_SHORTCUT}" shortcut
    SetShellVarContext all
    CreateShortCut "$SMPROGRAMS\logsquirl.lnk" "$INSTDIR\logsquirl.exe" "" "$INSTDIR\logsquirl.exe" 0
SectionEnd

; The file type page: .log and the Logcat traces checked, the optional types
; not. A silent install (/S) takes these defaults (#719).
!insertmacro LogSquirlFileTypeSections

Section "-File types changed"
    !insertmacro LogSquirlFileTypesChanged
SectionEnd

; Selected by default: the update check is on unless it is unticked here. The
; section itself installs nothing; the hidden one after it acts on the choice.
Section "${SECTION_TEXT_UPDATECHECK}" updatecheck
SectionEnd

; Always runs, so an install with the box ticked also removes the file an
; earlier install with it unticked left. While the file is there, LogSquirl
; does not check for updates, whatever its settings say
; (src/versioncheck/include/installoptout.h, #445).
; A silent install (/S) shows no component page, so nobody chose anything: it
; leaves the file as it is, and an administrator's opt-out survives an upgrade.
Section "-Update check choice"
    ${If} ${Silent}
        ; keep what an earlier install or an administrator left
    ${ElseIf} ${SectionIsSelected} ${updatecheck}
        Delete "$INSTDIR\logsquirl_no_update_check"
    ${Else}
        SetOutPath $INSTDIR
        FileOpen $0 "$INSTDIR\logsquirl_no_update_check" w
        FileClose $0
    ${EndIf}
SectionEnd

# Descriptions
!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
    !insertmacro MUI_DESCRIPTION_TEXT ${logsquirl} "The core files required to use logsquirl."
    !insertmacro MUI_DESCRIPTION_TEXT ${qtlibs} "Needed by logsquirl, you have to install these unless \
you already have the Qt development kit installed."
    !insertmacro MUI_DESCRIPTION_TEXT ${vcruntime} "Needed by logsquirl, you have to install these unless \
you already have the Microsoft Visual C++ 2017 Redistributable installed."
    !insertmacro MUI_DESCRIPTION_TEXT ${shortcut} "Create a shortcut in the Start menu for logsquirl."
    !insertmacro LogSquirlFileTypeDescriptions
    !insertmacro MUI_DESCRIPTION_TEXT ${updatecheck} "At most once a week, when it starts, LogSquirl downloads \
a small file from GitHub to see whether a newer version is out. Untick to turn this off for this installation."
!insertmacro MUI_FUNCTION_DESCRIPTION_END

# The components page shows the components and the file type page the file
# types (#719).
Function ComponentsPagePre
    !insertmacro LogSquirlHideFileTypeSections
    SectionSetText ${logsquirl} "${SECTION_TEXT_LOGSQUIRL}"
    SectionSetText ${qtlibs} "${SECTION_TEXT_QTLIBS}"
    SectionSetText ${vcruntime} "${SECTION_TEXT_VCRUNTIME}"
    SectionSetText ${shortcut} "${SECTION_TEXT_SHORTCUT}"
    SectionSetText ${updatecheck} "${SECTION_TEXT_UPDATECHECK}"
FunctionEnd

Function FileTypesPagePre
    SectionSetText ${logsquirl} ""
    SectionSetText ${qtlibs} ""
    SectionSetText ${vcruntime} ""
    SectionSetText ${shortcut} ""
    SectionSetText ${updatecheck} ""
    !insertmacro LogSquirlShowFileTypeSections
FunctionEnd

# Uninstaller
Section "Uninstall"
    Delete "$INSTDIR\Uninstall.exe"

    Delete "$INSTDIR\logsquirl.exe"
    Delete "$INSTDIR\logsquirl_grep.exe"
    Delete "$INSTDIR\logsquirl_crashpad_handler.exe"
    Delete "$INSTDIR\logsquirl_minidump_dump.exe"
    Delete "$INSTDIR\README.md"
    Delete "$INSTDIR\PRIVACY.md"
    Delete "$INSTDIR\logsquirl_no_update_check"
    Delete "$INSTDIR\COPYING"
    Delete "$INSTDIR\NOTICE"
    Delete "$INSTDIR\DOCUMENTATION.md"
    Delete "$INSTDIR\documentation.html"
    Delete "$INSTDIR\Qt5Widgets.dll"
    Delete "$INSTDIR\Qt5Core.dll"
    Delete "$INSTDIR\Qt5Gui.dll"
    Delete "$INSTDIR\Qt5Network.dll"
    Delete "$INSTDIR\Qt5Concurrent.dll"
    Delete "$INSTDIR\Qt5Xml.dll"
    Delete "$INSTDIR\Qt6Widgets.dll"
    Delete "$INSTDIR\Qt6Core.dll"
    Delete "$INSTDIR\Qt6Gui.dll"
    Delete "$INSTDIR\Qt6Network.dll"
    Delete "$INSTDIR\Qt6Concurrent.dll"
    Delete "$INSTDIR\Qt6Xml.dll"
    Delete "$INSTDIR\Qt6Core5Compat.dll"
    Delete "$INSTDIR\Qt6Svg.dll"
    Delete "$INSTDIR\platforms\qwindows.dll"
    RMDir "$INSTDIR\platforms"
    Delete "$INSTDIR\imageformats\qsvg.dll"
    RMDir "$INSTDIR\imageformats"
    Delete "$INSTDIR\iconengines\qsvgicon.dll"
    RMDir "$INSTDIR\iconengines"
    Delete "$INSTDIR\styles\qmodernwindowsstyle.dll"
    ; Clean up legacy Qt style plugins from previous installations
    Delete "$INSTDIR\styles\qwindowsvistastyle.dll"
    RMDir "$INSTDIR\styles"
    Delete "$INSTDIR\tls\qopensslbackend.dll"
    Delete "$INSTDIR\tls\qschannelbackend.dll"
    RMDir "$INSTDIR\tls"
    Delete "$INSTDIR\msvcp140.dll"
    Delete "$INSTDIR\msvcp140_1.dll"
    Delete "$INSTDIR\vcruntime140.dll"
    Delete "$INSTDIR\vcruntime140_1.dll"
    Delete "$INSTDIR\tbb12.dll"
    Delete "$INSTDIR\hs.dll"
    Delete "$INSTDIR\hs_avx2.dll"
    Delete "$INSTDIR\libcrypto-3-x64.dll"
    Delete "$INSTDIR\libssl-3-x64.dll"
    Delete "$INSTDIR\libcrypto-3.dll"
    Delete "$INSTDIR\libssl-3.dll"
    ; Clean up legacy OpenSSL 1.1 files from previous installations
    Delete "$INSTDIR\libcrypto-1_1-x64.dll"
    Delete "$INSTDIR\libssl-1_1-x64.dll"
    Delete "$INSTDIR\libcrypto-1_1.dll"
    Delete "$INSTDIR\libssl-1_1.dll"
    Delete "$INSTDIR\mimalloc.dll"
    Delete "$INSTDIR\mimalloc_override.dll"
    Delete "$INSTDIR\mimalloc_redirect.dll"
    Delete "$INSTDIR\mimalloc_redirect32.dll"
    Delete "$INSTDIR\mimalloc-redirect.dll"
    Delete "$INSTDIR\mimalloc-redirect32.dll"
    RMDir "$INSTDIR"

    ; Remove settings in %appdata%
    Delete "$APPDATA\logsquirl\logsquirl.ini"
    RMDir "$APPDATA\logsquirl"

    ; Remove the file associations: LogSquirl's ProgIDs and Open with entries,
    ; and each extension LogSquirl was the default for back to the ProgID it had
    ; before (#719); an earlier version's "Log file" association too. Before the
    ; Uninstall key, whose going tells a deployment that the uninstall is done.
    !insertmacro LogSquirlUnregisterFileTypes
    ${unregisterExtension} ".log" "Log file"
    DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\logsquirl"

    DeleteRegKey HKCR "*\OpenWithList\logsquirl.exe"
    DeleteRegKey HKCR ".txt\OpenWithList\logsquirl.exe"
    DeleteRegKey HKCR ".Log\OpenWithList\logsquirl.exe"
    DeleteRegKey HKCR ".cap\OpenWithList\logsquirl.exe"
    DeleteRegKey HKCR "Applications\logsquirl.exe\shell\open\command"
    DeleteRegKey HKCR "Applications\logsquirl.exe\shell\open"
    DeleteRegKey HKCR "Applications\logsquirl.exe\shell"
    DeleteRegKey HKCR "Applications\logsquirl.exe"

    ; The 'Send to' shortcut of the user uninstalling, who is usually the one
    ; who installed (#506)
    Delete "$SENDTO\logsquirl.lnk"

    ; Remove the shortcut, if any
    SetShellVarContext all
    Delete "$SMPROGRAMS\logsquirl.lnk"
SectionEnd

