name: "Build and test in container"
description: "Generate the build files, build the code and run the tests"
runs:
  using: "composite"
  steps:
    - name: Pre-seed CPM for sub-projects
      shell: sh
      run: |
        mkdir -p "$LOGSQUIRL_WORKSPACE/cpm_cache/cpm"
        cp "$LOGSQUIRL_WORKSPACE/cmake/CPM.cmake" "$LOGSQUIRL_WORKSPACE/cpm_cache/cpm/CPM_0.38.6.cmake"

    - name: configure
      shell: sh
      run: |
        docker run --env LOGSQUIRL_VERSION=$LOGSQUIRL_VERSION --env LOGSQUIRL_BUILD_ROOT=$LOGSQUIRL_BUILD_ROOT --env LOGSQUIRL_CMAKE_OPTS="$LOGSQUIRL_CMAKE_OPTS" -v "$LOGSQUIRL_WORKSPACE":/usr/local ${{ matrix.config.container }} /bin/bash -c "cmake -B /usr/local/$LOGSQUIRL_BUILD_ROOT $LOGSQUIRL_CMAKE_OPTS -DCPM_SOURCE_CACHE=/usr/local/cpm_cache /usr/local"

    - name: build
      shell: sh
      run: |
        docker run --env LOGSQUIRL_BUILD_ROOT=$LOGSQUIRL_BUILD_ROOT -v "$LOGSQUIRL_WORKSPACE":/usr/local ${{ matrix.config.container }} /bin/bash -c "cmake --build /usr/local/$LOGSQUIRL_BUILD_ROOT --target ci_build"
