name: "Make CI Release"

on:
  workflow_dispatch:
    inputs:
      ci-run-id:
        description: "Run ID of CI workflow"
        required: false

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download artifacts for last successful CI workflow
      if: ${{ !github.event.inputs.ci-run-id }}
      uses: dawidd6/action-download-artifact@v6
      with:
        workflow: ci-build.yml
        workflow_conclusion: success

    - name: Download artifacts for CI workflow with provided run id
      if: ${{ github.event.inputs.ci-run-id }}
      uses: dawidd6/action-download-artifact@v6
      with:
        workflow: ci-build.yml
        run_id: ${{ github.event.inputs.ci-run-id }}

    - name: Initialize version
      run: echo "LOGSQUIRL_VERSION=`cat logsquirl_version/logsquirl_version.txt`" >> $GITHUB_ENV

    - name: Display structure of downloaded files
      run: ls -R ./packages-*

    - name: Setup Sentry CLI
      uses: mathrix-education/setup-sentry-cli@0.1.0
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      with:
        token: ${{ secrets.SENTRY_TOKEN }}
        organization: anton-filimonov
        project: logsquirl

    - name: Create Sentry release
      shell: sh
      run: |
        sentry-cli releases new $LOGSQUIRL_VERSION
        sentry-cli releases set-commits --auto $LOGSQUIRL_VERSION

    - name: Upload symbols linux
      shell: sh
      run: |
        xz -d ./packages-jammy/logsquirl_jammy.debug.xz
        xz -d ./packages-noble/logsquirl_noble.debug.xz
        xz -d ./packages-oracle/logsquirl_oracle.debug.xz
        xz -d ./packages-fedora/logsquirl_fedora.debug.xz
        xz -d ./packages-appimage/logsquirl_appimage.debug.xz
        sentry-cli upload-dif ./packages-jammy/logsquirl_jammy.debug ./packages-jammy/logsquirl_jammy
        sentry-cli upload-dif ./packages-noble/logsquirl_noble.debug  ./packages-noble/logsquirl_noble
        sentry-cli upload-dif ./packages-oracle/logsquirl_oracle.debug ./packages-oracle/logsquirl_oracle
        sentry-cli upload-dif ./packages-fedora/logsquirl_fedora.debug ./packages-fedora/logsquirl_fedora
        sentry-cli upload-dif ./packages-appimage/logsquirl_appimage.debug  ./packages-appimage/logsquirl_appimage

    - name: Upload symbols mac
      shell: sh
      run: |
        sentry-cli upload-dif ./packages-macos-intel-qt6/logsquirl-x64.app/Contents/MacOS/logsquirl ./packages-macos-intel-qt6/logsquirl-x64.dSym
        sentry-cli upload-dif ./packages-macos-arm-qt6/logsquirl-arm64.app/Contents/MacOS/logsquirl ./packages-macos-arm-qt6/logsquirl-arm64.dSym

    - name: Upload symbols win
      shell: sh
      run: |
        sentry-cli upload-dif ./packages-windows-x64-qt6/logsquirl-$LOGSQUIRL_VERSION-x64-Qt6-pdb.zip

    - name: Cleanup release artifacts
      shell: sh
      run: |
        rm -rf ./packages-jammy/logsquirl_jammy
        rm -rf ./packages-noble/logsquirl_noble
        rm -rf ./packages-oracle/logsquirl_oracle
        rm -rf ./packages-fedora/logsquirl_fedora
        rm -rf ./packages-appimage/logsquirl_appimage
        rm -rf ./packages-macos-intel-qt6/logsquirl-x64.app
        rm -rf ./packages-macos-arm-qt6/logsquirl-arm64.app
        mkdir ./linux-debug
        mv ./packages-jammy/logsquirl_jammy.debug ./linux-debug
        mv ./packages-noble/logsquirl_noble.debug ./linux-debug
        mv ./packages-oracle/logsquirl_oracle.debug ./linux-debug
        mv ./packages-fedora/logsquirl_fedora.debug ./linux-debug
        mv ./packages-appimage/logsquirl_appimage.debug ./linux-debug
        tar -cJf ./linux-debug/logsquirl-$LOGSQUIRL_VERSION-symbols.tar.xz ./linux-debug/*
        rm ./linux-debug/*.debug

    - name: Prepare binary artifacts
      shell: sh
      run: |
        mkdir ./packages-bin
        mv ./packages-appimage/logsquirl_deps.tar.xz ./packages-bin/logsquirl-$LOGSQUIRL_VERSION-deps.tar.xz
        ar p  ./packages-jammy/logsquirl-$LOGSQUIRL_VERSION-jammy.deb data.tar.gz > ./packages-bin/logsquirl-$LOGSQUIRL_VERSION-bin.tar.gz
        mv ./logsquirl_version/logsquirl_version.txt ./packages-bin

    - name: Prepare checksums
      shell: sh
      run: |
        sha256sum --binary ./packages-bin/* ./packages-jammy/* ./packages-noble/* ./packages-oracle/* ./packages-fedora/* ./packages-appimage/*  > ./packages-bin/logsquirl-$LOGSQUIRL_VERSION-sha256.txt
        
    - name: Release win
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: ${{ secrets.LOGSQUIRL_GITHUB_TOKEN }}
        automatic_release_tag: continuous-win
        prerelease: true
        files: |
          ./packages-windows-x64-qt6/*

    - name: Release linux
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: ${{ secrets.LOGSQUIRL_GITHUB_TOKEN }}
        automatic_release_tag: continuous-linux
        prerelease: true
        files: |
          ./packages-jammy/*
          ./packages-noble/*
          ./packages-oracle/*
          ./packages-fedora/*
          ./packages-appimage/*
          ./packages-bin/*
          ./linux-debug/*

    - name: Release mac
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: ${{ secrets.LOGSQUIRL_GITHUB_TOKEN }}
        automatic_release_tag: continuous-osx
        prerelease: true
        files: |
          ./packages-macos-intel-qt6/*
          ./packages-macos-arm-qt6/*

    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_NEW_VERSIONS_WEBHOOK }}
        DISCORD_EMBEDS: '[{"title": "Windows", "url": "https://github.com/64x-lunicorn/LogSquirl/releases/tag/continuous-win"}, {"title": "Linux", "url": "https://github.com/64x-lunicorn/LogSquirl/releases/tag/continuous-linux"}, {"title": "Mac", "url": "https://github.com/64x-lunicorn/LogSquirl/releases/tag/continuous-osx"}]'
      uses: Ilshidur/action-discord@master
      with:
        args: 'New CI build {{LOGSQUIRL_VERSION}} has been released!'




   
